Updated `harmonized_sdd()` function
AquaSat/AquaMatch_harmonize_WQP pull request #103
Opened 2024-08-06 23:00 UTC by juandlt-csu

I have made the following updates to the harmonize sdd workflow based on my last PR:

- Minor data prep
    - Take absolute values from the original result column
- Remove fails
    - Fail text has been updated to be specific to SDD
    - remove activity and laboratory comment column here.
- Clean up MDLs
    - We just look for "<" to MDL, gets flagged post harmonization
- Clean up "greater than" values
    - We just look for ">" and some other special characters, gets flagged post harmonization
        - Keep the data and remove the equal size, do the same for the stars
    - Have been updated to match those updates in chla
    - The other instances of potentially salvageable data are not considered because they constitute far less than 1% of the total dataset.
- Clean up approximated values/Gap fill harmonized values with depth columns
    - Flagged pre-harmonization
    - There are instances of approximate language, but those are unrelated to SDD. Very few instances of "*"
    - Gap filling harmonized values with depth column information based on depth column criteria
        - flag 0 = value and units not adjusted
        - flag 1 = value filled using activity depth measure column
        - flag 2 = value filled using activity bottom depth measure column
    - Values that have been gap filled will be tier 3.
- Remove remaining NAs
    - If the value or units are empty we drop them. We do not attempt to fill in units with depth column information.
    - In my original PR the idea of retaining bottom values was floating around, but since we are not doing that that is no longer a consideration.
- Harmonize value units
    - In the PR there was an issue with dropping all the values that were NA due to bottom language in the original result column. I have been told that it's okay to drop those values now and to not worry about retaining them and the pipeline reflects that decision.
    - We drop rows where there is no unit to convert.
- Gap fill, harmonize, and flag bottom depth data
    - Flagged pre-harmonization
    - Use this step to gap fill and harmonize bottom depth and ignore the other bits that are in this step for chla.
        - flag 0 = bottom depth value not adjusted and no indication that SD hit bottom
        - flag 1 = bottom depth value adjusted due to indication that SD hit bottom
- Aggregate and tier analytical methods
    - Retain those methods that have "unspecified" in their value. The unrelated text strings have been updated.
    - Using harmonized_local_time to determine time that the observation was taken
    - Sdd_scope_tag has been updated and takes on an approach similar to that of bottom language. There is scope tag and negate scope tag language being considered now.
    - Tiers:
        - 0 = Restrictive. Time reported within the allotted window and method indicates use of viewscope.
        - 1 = Narrowed. Either time reported within the allotted window or method indicates use of viewscope, but not both.
        - 2 = Inclusive. Time not reported/time reported outside of window, and no indication of viewscope used.
        - 3 = Inclusive. harmonized value gap filled with depth column.
- Flag
    - MDLs
        - 0 = value not adjusted and value is greater than 0.01
        - 1 = original NA value adjusted using MDL method
        - 2 = provided value below 0.01; not adjusted
    - Greater than
        - 0 = value less than 31m with NO special characters
        - 1 = value less than 31m with special characters
        - 2 = value greater than 31m with NO special characters
        - 3 = value greater than 31m with special characters
    - Field methods
        - 0 = negate adverse text present (calm day)
        - 1 = neither negate key words nor key words present
        - 2 = key words related to adverse weather conditions present, no negate terms present (windy day)
    - Misc flag
        - 0 = no misc flag
        - 1 = bottom indicated
        - 2 = Harmonized value > bottom value
- Unrealistic values:
    - Not using this step. Values greater than 31m are flagged.
- Generate plots with harmonized dataset
    - Updated to match sdd updates
- Aggregate simultaneous records
    - Updates to simultaneous records have been incorporated
- Export
    - Updated to match sdd updates

2024-08-09 19:31 UTC, steeleb requested changes
Hey Juan!

Great job continuing to work through this!

I left a lot of comments, but most of them are straightforward, I think. LMK if you want to chat at all. I'm going to submit a PR to add the updated config, _targets, and 3d_harmonize_sdd to be able to work within the targets architecture more easily so that no one needs to recreate the wheel there.

2024-08-09 19:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  adverse_text <- paste0(c("wind", "chop", "choppy", "precipitation", "rain", "ice"),
Additionally, I think the 'wind' text might need to be a bit more specific, this is catching all the comments with wind direction, not actual indications of high/heavy/strong winds.

2024-08-09 19:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +        bottom_tag == 1 ~ 1,
```suggestion
        bottom_tag == 1 & negate_bottom_tag == 0 ~ 1,
```

2024-08-09 19:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +
Comment: There are a bunch of super unrealistic values in here (like, greater than 100m)... I know we flag things greater than 30, but I think we also need to filter completely unrealistic values.

2024-08-09 19:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +    group_by(parameter.x, OrganizationIdentifier, MonitoringLocationIdentifier,
I had to edit this to `parameter` to get it to run. :)

2024-08-09 19:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +           )) %>%
Suggestion: if you set these up as a factor with levels, you can add a label to it without adding a column AND the fig will be ordered correctly.

```
factor(tier, 
    levels = c(0,1,2,3), 
    labels = c("Restrictive (Tier 0)", "Narrowed (Tier 1)", "Inclusive (Tier 2)", "Inclusive (Tier 3)"))
```

2024-08-09 19:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +    scale_y_continuous(label = label_scientific()) +
Suggestion: this particular plot seems well-served to not have a log transformation , IMO.
```suggestion
```

2024-08-09 19:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +             tier == 3 ~ paste0("Inclusive (Tier 2) NAs removed: ", tier_3)
```suggestion
             tier == 3 ~ paste0("Inclusive (Tier 3) NAs removed: ", tier_3)
```
Also, see the suggestion about using factors above.

2024-08-09 19:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  write_csv(no_simul_chla,
```suggestion
  write_csv(no_simul_sdd,
```

2024-08-09 19:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      nrow(no_simul_chla)
```suggestion
      nrow(no_simul_sdd)
```

2024-08-09 19:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +    sdd_grouped_preagg_path = grouped_chla_out_path,
```suggestion
    sdd_grouped_preagg_path = grouped_sdd_out_path,
```

2024-08-09 20:01 UTC, mbrousil commented
@juandlt-csu Sorry, I haven't had a chance to review yet! Should be able look through this early next week.

2024-08-12 15:36 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +    mutate(ResultMeasureValue = abs(ResultMeasureValue)) %>%
This is the first and only step that alters data from this column (ResultMeasureValue) before we look for NA's in that column during the MDL step. I can move this out of this step and into the "MDL" or "greater than" step because both of those have to do with altering values that have special characters in them, and I would prefer that to adding them to the approximate flag because the definition of that flag is so different. However, if we do decide to put those values under the approximate flag because of their "-" special character, should we also move those values that have had "=" removed from them under the approximate flag as well? That would mean that the MDL step would only look for "<" special characters and the greater than step would only look for ">" special characters. 

TLDR: We can move this to just before the MDL step, but this is already the only alteration to the ResultMeasureValue column before that step (sans failure removal). We can add an approximate flag to cover these alterations as well, but it might make more sense to put them in the MDL or greater than step instead.

What do y'all think @steeleb  @mbrousil

2024-08-12 15:39 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  sdd_harmonized_values <- sdd_mdls_added %>%
I think this naming convention followed chla when is was trying to convert it over, but I think this change makes sense.

2024-08-12 15:50 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +    "unable", "reject", "no data", "Not Reported", "no reading"
Made these updates

2024-08-12 15:55 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  sdd_harmonized_values <- sdd_mdls_added %>%
made this update

2024-08-12 16:07 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +    scale_y_continuous(label = label_scientific()) +
This makes sense to me

2024-08-12 17:02 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +    mutate(ResultMeasureValue = abs(ResultMeasureValue)) %>%
I think functionally, it makes sense to deal with them before MDL/greater than (but in that same processing procedure. Essentially, we're altering the values, which could add uncertainty (say, that character was not supposed to be a '-' but a '9' or something), which we should document. In terms of the approximate flag for MDL/greater than, I don't think it's necessary because they are already flagged as such.

2024-08-12 17:08 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  fail_counts <- list("ResultCommentText", "ResultMeasureValue_original") %>%
```
table(sdd %>% 
    filter(grepl(paste(fail_text, collapse = "|"), ResultDetectionConditionText)) %>% 
    pull(ResultDetectionConditionText))
```

This results in 286 entries for the fail text "Not Reported" with no other fail text hits. Most of these do not carry any values in the `ResultMeasureValue_original` (i.e. contain NA or #VALUE!). Given how inconsequential dropping these would be I will add `ResultDetectionConditionText` to this step.

2024-08-12 17:52 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +
What should be the cutoff for realistic values? Double 31m?

2024-08-12 19:01 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +
That seems reasonable to me!

2024-08-12 19:05 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  adverse_text <- paste0(c("wind", "chop", "choppy", "precipitation", "rain", "ice"),
I'd lean towards the 2nd option, and let someone else play with that. If it were more rows with valuable info I'd consider doing more here, but just identifying when weather was reported seems like a good/sane way to deal with this

2024-08-12 20:26 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +                y = unit_conversion_table,
I think that is correct

2024-08-12 20:27 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +      # flag 2 = value filled using activity bottom depth measure column
Going to include the negative approximation in the misc flags

2024-08-12 20:40 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +      harmonized_bottom_depth_unit = if_else(!is.na(harmonized_bottom_depth_unit), "m", NA),
We will re-join the conversion table based on harmonized_bottom_depth_unit to resolve this, thanks B!

2024-08-13 17:41 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +    mutate(ResultMeasureValue = abs(ResultMeasureValue)) %>%
```
sdd_absvalues <- sdd_fails_removed %>%
    # Filter for negative sign
    filter(grepl("-", ResultMeasureValue))

sdd_absvalues <- sdd_fails_removed %>%
    # Filter for negative numbers (integers or floats)
    filter(grepl("^-\\d+(\\.\\d+)?$", ResultMeasureValue))
```

Both of these objects return 187 rows, do we want to add a flag for this?

2024-08-13 22:46 UTC, juandlt-csu commented
I have made the following updates to the harmonize SDD workflow based on this PR’s comments.
* Minor data prep:
    * Removed taking the absolute value from this step, and instead added a `Clean up special characters` step before the `Clean up MDLs` step.
* Clean up special characters:
    * Look for `-`, `=`, and `*` in the original value column and extract the number values. 
    * This step flags this data under miscellaneous flag 3 = Special characters present (*, =,-)
* Clean up “greater than” values
    * Remove `=` from this string search. Now only searches for `>`
* Clean up approximated values/Gap fill harmonized values with depth columns
    * Simplified the logic for the flagging criteria.
        * Only fill harmonized value if there is Activity depth data or bottom depth data.
        * Prefer to fill in with activity depth data
        * Only prefer bottom depth data if there is bottom language and no negate language
* Gap fill, harmonize, and flag bottom depth data
    * Re-joined the conversion table based on harmonized bottom depth for bottom depth gap fill unit conversion. Previously we had used the conversion column from the harmonized units conversion step under the assumption that these units would be the same.
* Flag
    * Converted adverse text to environmental conditions text. Field flag is now used to determine if there was environmental information stored in the comment columns instead of determining if there were good/bad weather conditions. 
* Unrealistic values:
    * Cutting off those values that are greater than 62m (double our cutoff for flagging suspiciously high values)
* General:
    * Made those updates that deal with downstream effects of these changes

2024-08-14 16:41 UTC, steeleb requested changes
So stinking close!! 

Just a few more tweaks. 

Additionally, can we round all the harmonized values that were converted to 2 decimal point precision to avoid false precision due to the conversion? I think this is as easy as `if_else(harmonized_units != ResultMeasureValue.Units, round(harmonized_value, 2), harmonized value)`

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      "Rows removed due to fail-related language: ",
quibble: I wonder if this should be percentage for consistency?

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +
comment: add `rm()` & `gc()` up here, too

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
>    greater_vals$greater_value <- as.numeric(
```suggestion
  # this will cause coercion errors, which is expected, as some values have additional characters in
  # them that cause this step to have errors.
  greater_vals$greater_value <- as.numeric(
```

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  )
```suggestion
  )
  
```

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  # Remove remaining NAs ----------------------------------------------------
```suggestion

  # Remove remaining NAs ----------------------------------------------------
```

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +     sdd_fails_removed)
```suggestion
  rm(sdd_approx_added)
```

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      "% of samples have bottom depths that can be back filled with harmonized values."
```suggestion
      "% of samples have no reported ActivityBottomDepthHeightMeasure.MeasureValue that can be 
      back filled with harmonized values where Secchi on bottom was indicated."
```

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      "Rows removed while assigning flags: ",
Flagging: n row or percent

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
>    )
Flagging: n row or percent

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
>    )
Flagging: n row or percent

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
>    )
Flagging: n row or percent

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      tier = if_else(approx_flag != 0, 3, tier)
Just need to adjust from new approx_flag 1 where we use abs for negative values
```suggestion
      tier = if_else(approx_flag > 1, 3, tier)
```

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +
suggestion: pop a percent dropped here for consistency

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  plotting_subset <- cleaned_flagged_sdd %>%
```suggestion
  plotting_subset <- realistic_sdd %>%
```

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  # ggsave(filename = "../AquaMatch_harmonize_WQP_old/scratch/figures/sdd_charname_dists.png",
```suggestion
```

2024-08-14 16:41 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +                                dropped_field, dropped_simul)
Looks like 11 & 13 are missing, 9 is duplicated.
![Screenshot 2024-08-14 at 10 38 54 AM](https://github.com/user-attachments/assets/1322988c-410c-40ac-bf49-c765c59d701d)

2024-08-14 18:56 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +      tier = if_else(approx_flag != 0, 3, tier)
approx_flag 1 is still when the value is approximated from `ActivityDepthHeightMeasure.MeasureValue` column. The negative value conversion now falls under the misc flag. Do you want me to update this so that it a record is tier 3 if it is flagged with the misc flag indicating a special character removal?

2024-08-14 19:09 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
>    )
updated to percent

2024-08-14 19:11 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
>    )
Updated to percent

2024-08-14 19:11 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  plotting_subset <- cleaned_flagged_sdd %>%
Updated

2024-08-14 19:12 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +      "Rows removed due to fail-related language: ",
Updated to percent

2024-08-14 19:22 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +                                dropped_field, dropped_simul)
Updated the tibbles and compiled dropped

2024-08-14 19:24 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +        )
Resolving this and related comments as they were fixed when we simplified the approximation code.

2024-08-14 19:24 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +        ((!is.na(ActivityDepthHeightMeasure.MeasureValue) & !is.na(ActivityDepthHeightMeasure.MeasureUnitCode)) |
Made this update to the simplified approximation logic as well.

2024-08-14 19:24 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +        (!is.na(ActivityBottomDepthHeightMeasure.MeasureValue) & !is.na(ActivityBottomDepthHeightMeasure.MeasureUnitCode))) &
Updated

2024-08-14 19:25 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +    group_by(parameter.x, OrganizationIdentifier, MonitoringLocationIdentifier,
Updated

2024-08-14 19:25 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +             ResultMeasure.MeasureUnitCode == ActivityDepthHeightMeasure.MeasureUnitCode) ~ 1,
Resolved per approximation logic simplification

2024-08-14 20:37 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      tier = if_else(approx_flag != 0, 3, tier)
Superb. You can leave as you wrote it then. 

``` 
          tier = if_else(approx_flag != 0, 3, tier)
```

2024-08-19 23:09 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +                      "ResultDetectionConditionText") %>%
question: Should `ActivityCommentText` be included here too? When I added it in there were a decent number of results for fail language.

2024-08-19 23:11 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +      if_all(.cols = c(ResultCommentText, ResultMeasureValue_original),
question: Should the same columns used on L53 above be included here?

2024-08-19 23:11 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +    # only want NAs in the altered value column and where there is a `<` and a number in the original values column...
```suggestion
    # only want NAs in the altered value column and where there is a `>` and a number in the original values column...
```

2024-08-19 23:15 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +      harmonized_comments = "Approximated during 'greater than' step")
suggestion: We don't have a `harmonized_comments` column in the chlorophyll data, so it would be ideal to make it so that it's not necessary here. Lmk if this was something I missed in the last meeting though

2024-08-19 23:18 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
suggestion: This section does a good job of working within the constraints of the previous harmonization script! I do think it would be clearer to readers/users if we didn't describe it as an "MDL" process. I'm flexible on this, but ultimately it feels like a square peg, round hole kind of situation to me. "Less than" is fine with me, like the "greater than" handling later on.

2024-08-19 23:19 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up approximated values/Gap fill harmonized values --------------------
suggestion: My personal preference here would be to describe the things happening in L271:370 as "gap filling" rather than approximation

2024-08-19 23:21 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +        approx_flag == 2 ~ ActivityBottomDepthHeightMeasure.MeasureValue,
Not sure, but I think this needs to be changed?
```suggestion
        approx_flag == 2 ~ ActivityBottomDepthHeightMeasure.MeasureUnitCode,
```

2024-08-19 23:24 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +      back filled with harmonized values where Secchi on bottom was indicated."
Suggestion: Could this print statement be clarified a little? I'm not entirely sure I understand the meaning. Perhaps:
```suggestion
      "% of samples have no reported ActivityBottomDepthHeightMeasure.MeasureValue.  These will be 
      back filled with harmonized values where Secchi on bottom was indicated."
```

2024-08-19 23:25 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # time_tag
suggestion: Can you include a short comment here outlining why time is being tagged?

2024-08-19 23:26 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +      harmonized_local_time = as.POSIXct(harmonized_local_time,
question: Can you use the `harmonized_utc` column for this? It's already in UTC. If not, I'd avoid writing over the original `harmonized_local_time` column here. Better to make a temporary column that gets removed instead.

2024-08-19 23:27 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # scope_tag
suggestion: Can you include a short comment here outlining why scope text is being tagged?

2024-08-19 23:28 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  comment_cols <- c("ActivityCommentText", "ResultCommentText")
issue: Where possible we should avoid reusing variable names because it's possible for someone to accidentally filter the wrong part of the dataset, e.g. if they're hopping around the script at all. Could you rename instances of `comment_cols` so that they're step-specific?

2024-08-19 23:30 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  tiered_methods_sdd <- sdd_scope_tag %>%
question: The output of this step contains instances where `tier == 1` and `time_tag == 2`. Is this expected?

2024-08-19 23:31 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # Slim the tiered product (post flagging)
issue: `sdd_tiering_record.csv` doesn't get exported here. This also caused an error when I ran the pipeline because `p3_sdd_tiering_record` is still expected but fails to run.

2024-08-19 23:33 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # combinations of the tags that already exist
suggestion: Could you clarify this comment? I wasn't sure what it meant, I think in particular "flag everything that hasn't been flagged yet"

2024-08-19 23:34 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  flagged_sdd <- tiered_methods_sdd %>%
suggestion: It feels to me like this section makes the `harmonized_comment` column redundant. That could be an easy way to offload the information stored there?

2024-08-19 23:35 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +        (harmonized_value <= 0.01) ~ 2,
question: What's the significance of 0.01 here? Sorry if I missed something!

2024-08-19 23:36 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +
suggestion: Could you include a short comment here indicating the source for 62m?

2024-08-19 23:37 UTC, mbrousil requested changes
Thanks for your patience, Juan! I left some comments and questions that need to be addressed. I think they all should be pretty straightforward but let me know if you have any questions about them.

2024-08-20 15:44 UTC, steeleb reviewed
Just a couple of tiny tweaks for consistency to go along with MB's review. I was able to run this without issue, but didn't dive deeply in!

2024-08-20 15:44 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      nrow(sdd_no_na) - nrow(converted_units_sdd)
```suggestion
      "Percentage of rows removed while converting units: ", #***
      round(((nrow(sdd_no_na)) - nrow(converted_units_sdd)/nrow(sdd_no_na)) * 100, 3)
```

2024-08-20 15:44 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      round((nrow(sdd_bottom_depth_added)-nrow(sdd_relevant))/nrow(sdd_bottom_depth_added)*100,3)
```suggestion
      round((nrow(sdd_bottom_depth_added)-nrow(sdd_relevant))/nrow(sdd_bottom_depth_added)*100,3), 
      " %"
```

2024-08-20 15:44 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      round((nrow(tiered_methods_sdd) - nrow(cleaned_flagged_sdd)) / nrow(tiered_methods_sdd) * 100, 3)
```suggestion
      round((nrow(tiered_methods_sdd) - nrow(cleaned_flagged_sdd)) / nrow(tiered_methods_sdd) * 100, 3),
      " %"
```

2024-08-20 15:44 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      "Percent of rows removed due to unlikely analytical methods: ",
```suggestion
      "Percentage of rows removed due to unlikely analytical methods: ",
```

2024-08-20 15:44 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      round((nrow(cleaned_flagged_sdd) - nrow(realistic_sdd)) / nrow(cleaned_flagged_sdd) * 100, 3)
```suggestion
      round((nrow(cleaned_flagged_sdd) - nrow(realistic_sdd)) / nrow(cleaned_flagged_sdd) * 100, 3),
      " %"
```

2024-08-20 15:44 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      round((nrow(sdd_no_na)) / nrow(sdd_approx_added) * 100, 2),
```suggestion
      round((nrow(sdd_no_na)) / nrow(sdd_approx_added) * 100, 3),
```

2024-08-20 15:44 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      round((nrow(realistic_sdd) - nrow(no_simul_sdd)) / nrow(realistic_sdd) * 100, 3)
```suggestion
      round((nrow(realistic_sdd) - nrow(no_simul_sdd)) / nrow(realistic_sdd) * 100, 3),
      " %"
```

2024-08-21 16:35 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +                      "ResultDetectionConditionText") %>%
`ActivityCommentText` was removed because a big portion of those rows that were removed did not pertain to SDD.

2024-08-21 16:36 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +      if_all(.cols = c(ResultCommentText, ResultMeasureValue_original),
Yes, updated.

2024-08-21 16:39 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +      harmonized_comments = "Approximated during 'greater than' step")
Hm, I forget where I got that from, maybe an old sdd script or the old chla script. I can just remove that column from this workflow, would that work?

2024-08-21 16:43 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
how does this fit with the naming conventions in the final dataset output, which has `mdl_flag` as an output.

2024-08-21 16:46 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +        approx_flag == 2 ~ ActivityBottomDepthHeightMeasure.MeasureValue,
Great catch!

2024-08-21 16:47 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
An alternative is that all of these could get lumped in with special characters.

2024-08-21 16:55 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +      harmonized_local_time = as.POSIXct(harmonized_local_time,
I will make a temporary column instead of overwriting the current harmonized_local_time column.

2024-08-21 17:00 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  tiered_methods_sdd <- sdd_scope_tag %>%
This is expected if `scope_tag == 0` in those cases, as it would fulfill the `exclusive or` condition.

2024-08-21 17:17 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +        (harmonized_value <= 0.01) ~ 2,
Values less than 0.01m are below our method detection limit. Flag 2 if the SDD reading was reported as less than 1 cm beneath the surface of the water.

2024-08-21 21:02 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  # Slim the tiered product (post flagging)
Updated

2024-08-22 17:15 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
I think that's a great idea @steeleb! It's probably the most conceptually consistent way to organize it too.

2024-08-22 17:15 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +      "% of samples have no reported ActivityBottomDepthHeightMeasure.MeasureValu. These will be
```suggestion
      "% of samples have no reported ActivityBottomDepthHeightMeasure.MeasureValue but Secchi on bottom has been indicated and a harmonized value is present. These will be 
```
There are additional conditions to describe the % of samples here. Added more context to add readabillity.

2024-08-22 17:17 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  # 3. Measurements beyond this point are considered improbable and likely erroneous.
```suggestion
  # 3. Measurements beyond this point are considered improbable and likely erroneous due to unit conversion or other data entry issues.
```

2024-08-22 17:31 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  comment_cols <- c("ActivityCommentText", "ResultCommentText")
Updated

2024-08-22 17:35 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
So we are going to remove the MDL flag altogether, and those values that are less that 0.01 will not get flagged?

2024-08-22 17:36 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  flagged_sdd <- tiered_methods_sdd %>%
Updated to offload harmonized_Comment here

2024-08-22 17:49 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +                      "ResultDetectionConditionText") %>%
```suggestion
  # Note that ActivityCommentText not included because fail comments were mostly about non-SDD data
  fail_counts <- list("ResultCommentText", "ResultMeasureValue_original",
                      "ResultDetectionConditionText") %>%
```

2024-08-22 18:31 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
I think there are two things happening here: 

1) we remove the special character '<' - which in some other parameters indicates BDL/MDL. We don't treat these data as MDL(I don't think...) but rather just remove the special character (which would be a reason to include '<' in special characters alongside '=' and '*'). We *could* add the MDL flag of 2 (MDL indicated, but value unchanged) in the instances where '<' is in the ResultMeasureValue and leave the code for removing that character as-is.

2) we also flag anything < 0.01 m as MDL (a flag of 2 currently, but maybe it should be 1, value reported <0.01, changed to 0.01) after unit conversion because that is the documented physical measure that we think is possible (a human can't discern less than 1cm resolution). 

There are two options here:
1) move "<" into the special character handling with "=" and "*" and not notate in MDL. This would leave MDL virtually blank because the 0.01 flagging happens so much later. Note that we may want to consider altering the harmonized value of anything <0.01 to 0.01. In this case, a MDL flag of 1 is not used and should probably be removed. 

2) Re-think this and change our flags/motivation so that "<" means MDL and it is flagged as such and incorporate these changes into the code. 

So here is what I think we should do:
      # Flag: 0 = value not adjusted and value is greater than 0.01m
      #       1 = original value <0.01m adjusted to 0.01m
      #       2 = original value contained "<" in ResultMeasureValue column, which was removed, but the value was unaltered

2024-08-22 18:37 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
Thanks for the explanation! I agree with your suggestion @steeleb.

@juandlt-csu is it possible to do the `mdl_flag` assignments in the MDL section rather than in the Flag section? If not I think it would at least be helpful to describe the MDL situation B has outlined in that section.

2024-08-22 21:47 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
We flag MDL during that step because it is after we harmonize the units, so I think it's best to keep the MDL flagging in the flagging section . Do we want go with option 1 or 2? I think option 2 makes more sense, since it's more in line with what we have so far.

2024-08-23 16:08 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
I agree, @juandlt-csu! Let's go for # 2 here - thanks for being flexible as we continually change the rules on you. :)

2024-08-23 16:09 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
Yep, agreed on option 2!

2024-08-23 16:53 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
Great, this will be just like a reverse `greater than` flag then.

2024-08-23 17:54 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +  # Clean up MDLs --------------------------------------------------------------
I've updated the `MDL` flag to be more in line with the `greater than` flag. The conversion of the sub-0.01m values to 0.01m happens in the `Realistic range of values` section (formerly `unrealistic values`), where I added a very short blurb about it and a print statement to know the percentage of rows that were converted.

2024-08-26 17:39 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +    # convert it to a number. This captures values like "<0.5", ignoring any text after the number.
@juandlt-csu can you just clarify this one - this is just removing the <, right?

2024-08-26 17:40 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  # Find MDLs and make them usable as numeric data
```suggestion
  # Find MDL character ("<") and make them usable as numeric data
```

2024-08-26 17:42 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  # gap filling the MDL ("less than") values, we can gap fill the results that
```suggestion
  #  the MDL ("less than") values, we can coerce the ResultMeasureValue that
```

2024-08-26 17:42 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +  # contain values greater than some amount.
```suggestion
  # contain a greater than symbol.
```

2024-08-26 18:02 UTC, steeleb reviewed
This looks phenomenal.

I have a handful of suggestions, most of which I admit are absolute nit picks, but important nonetheless. I think this can be merged after you address the handful of comments and after MB has re-reviewed.

B

2024-08-26 18:03 UTC, steeleb commented on 3_harmonize/src/harmonize_sdd.R
> +        approx_flag == 2 ~ ActivityBottomDepthHeightMeasure.MeasureValue,
oops, this needs to be committed too!

2024-08-26 20:25 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +      c("\\>" = "", "\\=" = "" )))
Correct, updated

2024-08-26 20:26 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +           harmonized_comments = ifelse(index %in% mdl_updates$index,
This column gets offloaded in the `flag` section

2024-08-26 20:26 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +                                        "Approximated during 'greater than' step",
Do we want to change this to "cleaned" instead?

2024-08-26 20:48 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +    # the number, and ensures the result is positive.
Updated. Solution here was to exclude samples with alphabetical characters from the filter before we extract the number.

2024-08-26 20:49 UTC, juandlt-csu commented on 3_harmonize/src/harmonize_sdd.R
> +                                        "Approximated during 'greater than' step",
Changed this language to cleaned

2024-08-27 18:57 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # Find MDL character ("<") and make them usable as numeric data
```suggestion
  # Find "less than" ("<") characters and make them usable as numeric data.
  # For other parameters finding "<" more directly relates to method detection
  # limits, but for consistency with flagging columns across datasets we use
  # the same naming conventions for SDD.

```

2024-08-27 19:06 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +  # Aggregate and tier analytical methods -----------------------------------
```suggestion
# Aggregate analytical methods --------------------------------------------
```

2024-08-27 19:06 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
>      short_reason = "Analytical methods",
```suggestion
    short_reason = "Aggregate methods",
```

2024-08-27 19:07 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +
```suggestion


 # Tier analytical methods -------------------------------------------------

```

2024-08-27 19:11 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +    short_reason = "Analytical methods",
```suggestion
    short_reason = "Tier methods",
```

2024-08-27 19:13 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +    # the mena value (harmonized_value in this case)
```suggestion
    # the mean value (harmonized_value in this case)
```

2024-08-27 19:14 UTC, mbrousil commented on 3_harmonize/src/harmonize_sdd.R
> +    # Calculate coefficient of variation as the standardard deviation divided by
```suggestion
    # Calculate coefficient of variation as the standard deviation divided by
```

2024-08-27 19:17 UTC, mbrousil approved these changes
Thanks Juan! This looks good. Just a couple of small edits from me and then it can be merged in.

2024-08-28 17:35 UTC, merged