SDD bookdown & pre-review cleanup
AquaSat/AquaMatch_harmonize_WQP pull request #106
Opened 2024-09-12 03:28 UTC by mbrousil

Hey @steeleb!

This is a large PR, but as is often the case a lot of it is the result of bookdown knitting and pipeline outputs. There's a couple of things I had already committed before SDD came through, so there's minor changes related to DOC and True Color, neither of which is that substantial (nor time sensitive).

The major thing in need of review is the new SDD chapter of the bookdown (`bookdown_raw/06_sdd_harmonization.Rmd` and its html outputs). In an ideal world I'd send out the SDD packet for USGS review ~Monday but don't feel rushed if you need more time to look over this. In addition to the bookdown changes I've also made edits to `3_harmonize/src/harmonize_sdd.R` for formatting and standardization with the chlorophyll workflow.

Thanks!

2024-09-16 23:19 UTC, steeleb requested changes
Hey MB!

Thanks for your patience here. Just some small tweaks:

1) pre-harmonization for SDD may merit something slightly different. see note for MVP in Rmd
2) suggestion to remove some methods from the filtering of analytical methods, suggestions in .Rmd
3) adding additional context/justification for tiering and dropping in Rmd (copied from sdd harmonization script)

After those are settled, this is g2g.

2024-09-16 23:19 UTC, steeleb commented on bookdown_raw/06_sdd_harmonization.Rmd
> +Those harmonized depth columns are:
```suggestion
There are four columns that explicitly contain depth information for a given WQP entry. Of these columns we are only interested in the `ActivityBottomDepthHeightMeasure.MeasureValue` column for Secchi disk depth because it may be an indicator of the bottom of the water body for a given WQP entry. Here we harmonize the values in the bottom depth column. To keep this data in line with the rest of the data in AquaSat v2, the other harmonized depth columns are filled with `NA` since Secchi disk depth is a discrete depth measurement. Those harmonized depth columns are:
```

2024-09-16 23:19 UTC, steeleb commented on bookdown_raw/06_sdd_harmonization.Rmd
> +We check the `ResultAnalyticalMethod.MethodName` column for names that indicate non-Secchi disk depth measurements. Phrases used to flag and remove unrelated methods for Secchi disk depth data are: "
Note: Sorry I didn't catch this earlier, but I think we should remove "no information exists for method", "not available", "other or unknown procedure", "qa", "unknown", "unkown", "unspecified" from this list to be inclusive. One may often take two SDD measurement and call one QA, and others may not indicate a specific method because it's a field method. Maybe this is a @matthewross07  and @mishafredmeyer question tho. We drop more than 1% of the samples here, which is the reason I am even suggesting this.

2024-09-16 23:19 UTC, steeleb commented on bookdown_raw/06_sdd_harmonization.Rmd
> +| 2        | Inclusive   | Data that are assumed to be reliable and are harmonized to our best  ability given the information available from the data provider. This  tier includes  NA or non-resolvab
```suggestion
| 2        | Inclusive   | Data that are assumed to be reliable and are harmonized to our best  ability given the information available from the data provider. | Time not reported/was outside of 10am-2pm/was 11:59:59 and no indication that viewscope was used                  |
```

2024-09-16 23:19 UTC, steeleb commented on bookdown_raw/06_sdd_harmonization.Rmd
> +
Suggestion: add the notes from the harmonization script here about why these things are important. 
```
   # Time tagging: Categorize timestamps to identify optimal conditions for
  # Secchi disk depth measurements.
  # Tag 0 (10am-2pm) represents the ideal time range for measurements due to
  # consistent lighting conditions. This helps in assessing data quality and
  # reliability of Secchi disk depth readings.
# Scope tagging: Identify whether a viewscope was used during Secchi disk
  # depth measurements.
  # Using a viewscope can significantly improve measurement accuracy by
  # reducing surface glare and wave effects. This tagging helps in assessing
  # the reliability and consistency of the  Secchi disk depth data across
  # different measurement conditions.
```

2024-09-16 23:19 UTC, steeleb commented on bookdown_raw/06_sdd_harmonization.Rmd
> +Before finalizing the dataset we removed Secchi disk depth values that were beyond a realistic threshold. We used 62 m as our cutoff for removal because it is double the limit for our `greater_flag`.
Can you incorporate more from the notes in the SDD script here, please? 

```
# We exclude reported Secchi disk depth (SDD) measurements exceeding
  # 62 meters from the final dataset.
  # This threshold is established based on the following rationale:
  # 1. SDD values greater than 31 meters are flagged as potentially anomalous
  #    in our quality control process.
  # 2. The 62-meter threshold represents a doubling of this initial flagging criterion.
  # 3. Measurements beyond this point are considered improbable and likely
  #    erroneous due to unit conversion or other data entry issues.
  # 4. Removing these extreme outliers enhances the overall reliability and
  #    interpretability of the dataset.
  # 5. This conservative approach aims to minimize the inclusion of potentially
  #    spurious data while preserving legitimate measurements within expected
  #    ranges for typical aquatic environments.
```

2024-09-17 15:52 UTC, mbrousil commented on bookdown_raw/06_sdd_harmonization.Rmd
> +Before finalizing the dataset we removed Secchi disk depth values that were beyond a realistic threshold. We used 62 m as our cutoff for removal because it is double the limit for our `greater_flag`.
Is there a citation or something that we can use to justify the 31m limit? I removed that text because the stated logic was more internally referential than based on, e.g. a paper or figure we could reference. In its current state it matches up well with the section from the chlorophyll document: 

`Before finalizing the dataset we remove chlorophyll a values that are beyond a realistic threshold. We use 1000 ug/L as our cutoff for removal (Wetzel, 2001, Chapter 15, Figure 19).`

2024-09-17 16:36 UTC, steeleb commented on bookdown_raw/06_sdd_harmonization.Rmd
> +Before finalizing the dataset we removed Secchi disk depth values that were beyond a realistic threshold. We used 62 m as our cutoff for removal because it is double the limit for our `greater_flag`.
I don't recall where 31 came from and I can't find it in any communications. 

Want to recode to 44m (citing Crater Lake, Larson, D.W. 1972. Temperature, transparency, and phytoplankton productivity in Crater Lake, Oregon. Limnol. Oceanogr. 17: 410-417.) and 80m (citing the theoretical maximum, Gieskes, W.W.C., C. Veth, A. Woehrmann, and M.Graefe 1987. Secchi disc visibility world record Shattered. EOS, Transactions, American Geophysical Union. 68:123.)?

This is from the overview from NALMS https://www.nalms.org/secchidipin/monitoring-methods/the-secchi-disk/secchi-records/

2024-09-17 16:39 UTC, mishafredmeyer commented on bookdown_raw/06_sdd_harmonization.Rmd
> +We check the `ResultAnalyticalMethod.MethodName` column for names that indicate non-Secchi disk depth measurements. Phrases used to flag and remove unrelated methods for Secchi disk depth data are: "
Hm, this is tricky... I have no firm opinion on this, but I do lean towards making all of these methods as "Inclusive", especially since all of them would drop more than 1% of samples. However, I don't want this decision to drastically delay things beyond the week if possible... @mbrousil -- if we instituted these changes, would it take much time for you to edit the bookdown and/or metadata?

2024-09-17 17:37 UTC, mbrousil commented on bookdown_raw/06_sdd_harmonization.Rmd
> +Before finalizing the dataset we removed Secchi disk depth values that were beyond a realistic threshold. We used 62 m as our cutoff for removal because it is double the limit for our `greater_flag`.
Ok awesome, thanks!

2024-09-18 20:23 UTC, mbrousil commented on bookdown_raw/06_sdd_harmonization.Rmd
> +3. The result comment column contains any user-provided text indicating a missing value, currently including: `analysis lost`, `not analyzed`, `not recorded`, `not collected`, or `no measurement take
Ok I think this should be addressed in 7875bd79d82de612137a5a27d772e917d0f818ce now

2024-09-18 20:29 UTC, mbrousil commented on bookdown_raw/06_sdd_harmonization.Rmd
> +These statuses generally indicate a reliable result having been reached, however we also include `NA` in an effort to be conservative. More specifically, when making decisions for this and other colu
Looks like there's no NAs here for SDD

2024-09-18 20:42 UTC, mbrousil commented on bookdown_raw/06_sdd_harmonization.Rmd
> +
Now addressed in ba7c5d659fd240cd77abac65c943015e6262b0dc

2024-09-18 20:49 UTC, mbrousil commented on bookdown_raw/06_sdd_harmonization.Rmd
> +Before finalizing the dataset we removed Secchi disk depth values that were beyond a realistic threshold. We used 62 m as our cutoff for removal because it is double the limit for our `greater_flag`.
Should now be addressed by 08be52555f889360e8b5d9066cb4dfe2e36c6761 and preceding commits

2024-09-19 16:52 UTC, steeleb approved these changes
Superb! Just a couple of edits to reflect the updated secchi-specific clean_wqp_data() and the updated ResultAnalyticalMethod.Method name text, which requires one more re-render on your end.

It might be a me problem, but some of the pngs are still not showing in the sdd .html. I'd just encourage a quick check of the website to make sure all figs are showing up there when this is integrated into the main repo.

2024-09-19 17:09 UTC, merged