Uploading SDD harmonization .Rmd to src folder
AquaSat/AquaMatch_harmonize_WQP pull request #96
Opened 2024-05-24 20:50 UTC by juandlt-csu

I am uploading the SDD harmonization .Rmd to the src folder so that it can be converted to a function once it has been approved.

Pre-processing step: the first section of this file pre-processes the data in the same way that it is processed in the targets pipeline when I was working in it. 

Harmonization step: the second section is where I tried to convert the chl-a harmonization function structure for sdd, but there were issues with this conversion so some adjustments had to be made. Those being:
- General Method Tier instead of Analytical tier: 
    - time tag and scope tags were created instead of the tags used in chl-a. These tags were used in determining the tier of the data.
        - Time tag uses UTC, this is probably wrong. 
- General Data Flags: 
    - field_flag: flags relating to field conditions and whether or not the secchi hit the bottom
    - depth_flag: run as it was made for chl-a - mdl_flag: flag based on whether a measurement is above or below 0.01 m.
    - approx_flag: run as it was made for chl-a 
    - greater_flag: flag based on '>' or '<' symbols in the data, and if the measurement is greater than 31m.
- Unit conversion was done earlier in the workflow because subsequent steps relied on this conversion.

2024-05-28 17:05 UTC, steeleb commented
I'll take a peek at this by EOD tomorrow!

2024-06-04 02:22 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +fail_text <- c(
note: It looks to me like `fail_text` is updated to be specific to SDD here, which is good! The current chla script has "outside of accept", which isn't in this list. It looks like it would return some records from `ResultCommentText` if it was included. However it's unclear to me if they're relevant to SDD. Basically, flagging this in case it wasn't intentionally excluded here.

2024-06-04 02:23 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +         approx_flag = ifelse(index %in% sdd_approx$index, 1, 0))
question: Looks like nothing had to be rescued from approximations. Does that sound right?

2024-06-04 02:24 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +rm(sdd_mdls_add)
typo: 
```suggestion
rm(sdd_mdls_added)
```

2024-06-04 02:25 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +them here.
Yep, I think that [this section](https://github.com/AquaSat/AquaMatch_harmonize_WQP/blob/614524cdbd33a464ce1aad5faff3cd5c5bf54a0e/3_harmonize/src/harmonize_chla.R#L148) in the chla MDL does this? But if not, can ignore because <1% of rows affected

2024-06-04 02:27 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +```{r Clean up "greater than" values}
There have been some bug fixes in this and similar sections where things were getting overlooked in chla, so it would be good to check this code against the current state of chla's steps, where relevant

2024-06-04 02:28 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +    round((nrow(greater_vals)) / nrow(sdd_mdls_added) * 100, 9),
I think I must have overwritten a more sensible number of digits to round to earlier in this repos history. We should probably use 1 across the board?
```suggestion
    round((nrow(greater_vals)) / nrow(sdd_mdls_added) * 100, 1,
```

2024-06-04 02:31 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +         greater_flag = case_when(
There's some `harmonized_values` that aren't being converted properly. It looks like some (not sure if all) had `">[value]"` and when units were changed the values themselves weren't converted. (And also note that values >31 are not getting caught with flag = 2). Examples: 
```r
sdd_harmonized_values %>%
  filter(greater_flag == 1) %>%
  select(ResultMeasureValue_original, ResultMeasure.MeasureUnitCode,
         harmonized_units, harmonized_value, greater_flag) %>%
  View()
```

2024-06-04 02:38 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +           .default = NA_integer_
issue: It looks like the logic here isn't functioning entirely as intended. I don't think there should be any NA's for flag carried forward, right? Some `greater_flags` are being assigned `NA` but might belong elsewhere.
+ Values exactly 31 are getting lost in the flagging, so maybe flag = 0 should be `<= 31` ?
+ Examples of some other potentially salvageable instances that are going in NA: units included in the value col (e.g., "19 FT", "0.5M"); equals sign included, presumably from an Excel formula? (e.g., "=3.50"); feet indicated with a tick mark (e.g., "11'", "15'3""); cases where a comma is used in place of a decimal point (e.g., "2,6")

These might not all be worth chasing down given their row counts, but for common, easily-caught cases I generally try to address them.

2024-06-04 02:40 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +unrelated_text <- paste0(c("chlorophyll", "sulfate", "sediment", "5310", "counting",
question: The inclusion of "unspecified" in `unrelated_text` is causing two secchi-related method names, "Secchi Disk Depth Readings-Unspecified Details" & "Secchi Disk-Unspecified cm", to be dropped. The first of these has almost 2k records. Should we keep it? Given row counts it's not worth it if it's a significant amount of work

2024-06-04 02:40 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +sdd_relevant <- flagged_depth_sdd %>%
question: One of the methods that remains in `sdd_relevant` is "Zebra/Quagga Mussel APHA 10200G Modified". Should we drop this? Another one I'm curious about (only 37 records tho) is "Meteorological Data Aboard the R/V Lake Guardian"

2024-06-04 02:45 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +sdd_time_tag <- sdd_relevant %>%
thought:
+ Probably can be updated/simplified once the [pending PR](https://github.com/AquaSat/AquaMatch_harmonize_WQP/pull/97) is merged. Is the goal to use local time for this? `harmonized_local_time` is the new column for that, and `harmonized_utc` is the other
+ Also would something like [this function](https://rdrr.io/cran/photobiology/man/sun_angles.html) be a potential shortcut instead of relying on parsing date and time like this? (i.e., calc local sun info directly from geoloc and UTC time). Note that I haven't used that package before, just brainstorming
 
question:
+ Should there be any NAs? I know that the `case_when()` statement here allows for them, but ideally this is 0, 1, or 2 and not NA, right?

2024-06-04 02:50 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +sdd_scope_tag <- sdd_time_tag %>%
issue: When I ran this locally I ran into two problems here:
1. 95% of the records in `sdd_scope_tag` are NA for `scope_tag`. Is that expected? It seems like they should all be 0 or 1?
2.  Some records that contain "scope" or "viewscope" are actually saying that those tools **weren't** used, e.g. "Seen on Bottom: No; Viewscope: No; Shady/sunny: Shady; Sunglasses: No;"

suggestion: Here's a suggestion to condense the scope tagging code below and address issue 1 above. Note that it **doesn't** address the second issue though!
```r
sdd_time_tag %>%
  mutate(
    scope_tag = if_else(
      condition = if_any(
        .cols = c(ResultAnalyticalMethod.MethodName, ActivityCommentText,
                  ResultLaboratoryCommentText, ResultCommentText,
                  ResultMeasureValue_original, USGSPCode),
        .fns = ~grepl(pattern = "scope|viewscope|72187",
                      x = .x,
                      ignore.case = TRUE)
      ),
      true = 0,
      false = 1
    )
  )
```

2024-06-04 02:53 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +tiered_methods_sdd <- sdd_scope_tag %>%
issue: I think the categorization logic here might need some work based on `tiering_record`:
+ NAs introduced in the two previous tagging steps affect the way that categorization is happening
+ Some records have a `0` for either `scope_tag` or `time_tag` but still get put in tier `2`. From what I understand this shouldn't be the case, right? (but this is complicated by the fact that these are records where one of those two cols is NA)
+ Is it OK that the `time_tag` logic in the `case_when()` only mentions cases where the tag is `0`? It seems like that might be fine, but I wasn't sure because our secchi formatting reference doc refers to the tier logic as the addition of values from two binary columns

2024-06-04 02:55 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +                    collapes = "|")
typo:

```suggestion
key_words <- paste0(c("wind", "chop", "choppy", "precipitation", "rain", "ice"),
                    collapse = "|")
```

2024-06-04 02:57 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +field_flagged_sdd <- cleaned_tiered_methods_sdd %>%
suggestion: 12.8K rows are NA for `field_flag`, and around 62K if I change the "collapse" line above - I suggest using the code structure I provided for the `scope_tag` section to rework this. I think it could save some lines too!

2024-06-04 02:58 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +```{r Aggregate simultaneous records}
note: This is one of the sections that's undergone changes through us preparing the chlorophyll a dataset. There have been changes to the grouping columns, the summary stats and columns in the aggregated dataset, figures, etc.

2024-06-04 03:02 UTC, mbrousil requested changes
Hey Juan! Thanks for developing this while I have been deep in the chlorophyll a revisions and especially for highlighting the differences from the chlorophyll a process. This will be a good jump forward for us for the secchi data product. It looks like you have essentially all of the major harmonization decisions figured out. I've commented on places where the code logic for those harmonization choices will need to be refined some, but I think we've got some good reference points for that in the chlorophyll scripts.

In addition to the comments in the code, there's a couple other points we'll need to address to get this into the larger pipeline. You and B might already have ideas about how to do this (who is able to, etc.), but feel free to use the Teams group to discuss details. Here's what comes to mind for me:
1. We'll need to bring this up to date with the current structure of the targets workflow, because there's been structural changes to the whole harmonization pipeline since you began working on secchi. For example, some datasets are now broken out by parameter and variable names have changed accordingly, site type metadata is added before harmonization, times and dates are cleaned up and reformatted before harmonization, and probably some other stuff I'm not thinking of right now
2. Through the process of harmonizing chlorophyll and making revisions we've caught and fixed some bugs in the chlorophyll script that are relevant to secchi (and all other params) as well, so we'll need to incorporate those changes here
3. Larger picture, we need to convert the script into targets steps and functions

Let me know if you have questions! And thanks again for tackling this.

2024-06-12 21:23 UTC, steeleb reviewed
Nice work Juan!!

I've added a bunch of comments, but lost steam about 2/3 through (sorry!) - much of the notes here are running comments/thoughts that I had while walking through this Rmd. 

1) I think we should have a quick chat with MB and @matthewross07 (and maybe MM) about whether any of the more dense code suggestions should be instituted before you go about them. I tried to add justifications for when I undoubtedly forget why I went down any one particular rabbit hole. 

2) after that, I think it would be worth it to start moving the first handful of steps (maybe up to MDL handling) into {targets}? This gives us time to work out any remaining updates in the chl-a pipeline before approaching any of the later steps that MB has fine tuned!

Let's see what @matthewross07 has to say and see if we should schedule a quick meetup to discuss any of the comments!

2024-06-12 21:23 UTC, steeleb commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +unrelated_text <- paste0(c("chlorophyll", "sulfate", "sediment", "5310", "counting",
I agree that we should try to retain those!

2024-06-17 15:52 UTC, juandlt-csu commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +         approx_flag = ifelse(index %in% sdd_approx$index, 1, 0))
That's correct

2024-06-17 15:56 UTC, juandlt-csu commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +them here.
Oh nice, I will incorporate it into MDLs step to maintain consistency across parameters.

2024-06-17 16:17 UTC, juandlt-csu commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +sdd_relevant <- flagged_depth_sdd %>%
We can remove those records

2024-06-17 16:36 UTC, juandlt-csu commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +sdd_time_tag <- sdd_relevant %>%
- Is harmonized_local_time always in MST or is it local relative to the sample? If it is local relative to the sample, then I can consider using that function. 
- Ideally there are no NAs, though I wonder if the same issue that you caught with the values being exactly 31 can have some NAs here, I will check.

2024-06-17 20:51 UTC, juandlt-csu commented
Closing PR to make suggested updates.

2024-06-17 20:51 UTC, closed without merging

2024-06-21 17:35 UTC, juandlt-csu commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +           .default = NA_integer_
I will try to address those NAs. I think those are being NA'd during the unit harmonization step.

2024-06-21 22:52 UTC, mbrousil commented on 3_harmonize/src/harmonizing_sdd_final.Rmd
> +sdd_time_tag <- sdd_relevant %>%
The tz that goes with `harmonized_local_time` will now be provided in `harmonized_tz`. Lmk if you need an updated version of the data, or perhaps @steeleb can run it locally to get it past the time processing step? I think you said that you can't run the pipeline locally due to RAM